USE [BDSIGAC6]
GO

ALTER TABLE [dbo].[SPTMA710] ADD  PT710NORD CHAR(6) DEFAULT ('') NOT NULL 
GO

ALTER TABLE [dbo].[SPTMA710] ADD  PT710NITE CHAR(2) DEFAULT ('') NOT NULL
GO

ALTER TABLE [dbo].[SPTMA710] ADD  PT710CDES CHAR(3) DEFAULT ('') NOT NULL
GO